import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import {
  LIST_SQL,
  addDelegateSql,
  addMemberSql,
  createRoadmapSql,
  removeDelegateSql,
  removeMemberSql,
} from './roadmaps-sql.mjs'

// Roadmaps, and who reaches them. Every person has one roadmap; a service
// token signs in like a person, so it is a member too. The MCP server's own
// token is a delegate: it acts on behalf of the member it names.
//
//   node tools/roadmaps/roadmaps.mjs --local  list
//   node tools/roadmaps/roadmaps.mjs --remote create "Their roadmap" --member them@example.com
//   node tools/roadmaps/roadmaps.mjs --remote create "Their roadmap" --template templates/starter.json
//   node tools/roadmaps/roadmaps.mjs --remote add-member 2 them@example.com
//   node tools/roadmaps/roadmaps.mjs --remote remove-member them@example.com
//   node tools/roadmaps/roadmaps.mjs --remote add-delegate <the MCP server's client id>
//   node tools/roadmaps/roadmaps.mjs --remote remove-delegate <client id>
//
// --env preview works on the test database instead of the real one, as in
// `--remote --env preview create "Tester" --member tester@example.com`.
//
// `create` fills the roadmap from templates/starter.json unless --template names
// another file, or --empty asks for none. Until the first member is ever added,
// whoever Access lets in reaches roadmap 1; from then on only members reach
// anything, for good, so add yourself before anyone else — and before letting
// anyone new past Access.

const USAGE = `Usage: node tools/roadmaps/roadmaps.mjs --local|--remote [--env preview] <command>
  list
  create <name> [--template <file> | --empty] [--member <principal>]
  add-member <roadmap id> <principal>
  remove-member <principal>
  add-delegate <principal>
  remove-delegate <principal>`

const root = new URL('../../', import.meta.url)
const args = process.argv.slice(2)
const where = args.shift()
if (where !== '--local' && where !== '--remote') fail(USAGE)

function fail(message) {
  console.error(message)
  process.exit(1)
}

/** The value after a flag, taken out of args. */
function option(flag) {
  const at = args.indexOf(flag)
  if (at === -1) return undefined
  const value = args[at + 1]
  if (value === undefined || value.startsWith('--')) fail(`${flag} needs a value`)
  args.splice(at, 2)
  return value
}

function flag(name) {
  const at = args.indexOf(name)
  if (at === -1) return false
  args.splice(at, 1)
  return true
}

// The database by its binding, so wrangler picks the one the environment names.
const env = option('--env')
const database = env === undefined ? ['DB'] : ['DB', '--env', env]
const command = args.shift()

function query(sql) {
  const stdout = execFileSync(
    'npx',
    ['wrangler', 'd1', 'execute', ...database, where, '--json', '--command', sql],
    { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 },
  )
  // Wrangler may print a banner before the JSON payload.
  const start = stdout.indexOf('[')
  if (start === -1) throw new Error(`No JSON in wrangler output for: ${sql}`)
  return JSON.parse(stdout.slice(start))[0].results
}

function execute(statements, what) {
  mkdirSync(new URL('build/', root), { recursive: true })
  const file = new URL('build/roadmaps.sql', root)
  writeFileSync(file, `-- Generated by tools/roadmaps/roadmaps.mjs: ${what}\n\n${statements.join('\n\n')}\n`)
  execFileSync('npx', ['wrangler', 'd1', 'execute', ...database, where, '--file', file.pathname], {
    stdio: 'inherit',
  })
}

const noMembersYet = () => query('SELECT COUNT(*) AS n FROM members_required')[0].n === 0

function warnIfFirst(wasEmpty, principal) {
  if (!wasEmpty) return
  console.log(
    `\n${principal} is the first member. From now on only members reach a roadmap:` +
      ' add everyone else, yourself included, with add-member.',
  )
}

switch (command) {
  case 'list': {
    const rows = query(LIST_SQL)
    for (const row of rows) {
      console.log(
        `${row.id}  ${row.name}  ·  ${row.items} items  ·  ${row.members ?? 'no members'}  ·  since ${row.created_at.slice(0, 10)}`,
      )
    }
    const delegates = query('SELECT principal FROM delegates ORDER BY principal')
    console.log(`delegates: ${delegates.map((row) => row.principal).join(', ') || 'none'}`)
    if (rows.length > 0 && noMembersYet()) {
      console.log('No members yet: whoever Access lets in reaches roadmap 1.')
    }
    break
  }

  case 'create': {
    const empty = flag('--empty')
    const templatePath = option('--template') ?? (empty ? undefined : 'templates/starter.json')
    const member = option('--member')
    const name = args.shift()
    if (!name) fail(USAGE)

    let template
    let version
    if (templatePath !== undefined) {
      const path = new URL(templatePath, root)
      if (!existsSync(path)) fail(`${templatePath} not found`)
      const raw = readFileSync(path, 'utf8')
      template = JSON.parse(raw)
      version = createHash('sha256').update(raw).digest('hex').slice(0, 12)
    }

    const wasEmpty = member !== undefined && noMembersYet()
    const id = query('SELECT COALESCE(MAX(id), 0) + 1 AS next FROM roadmaps')[0].next
    execute(
      createRoadmapSql({ id, name, now: new Date().toISOString(), template, version, member }),
      `create roadmap ${id}`,
    )
    console.log(
      `\nroadmap ${id} "${name}"${templatePath ? ` from ${templatePath}` : ', empty'}` +
        `${member ? `, for ${member}` : ''}`,
    )
    warnIfFirst(wasEmpty, member)
    break
  }

  case 'add-member': {
    const [roadmapId, principal] = args
    if (!roadmapId || !principal) fail(USAGE)
    const wasEmpty = noMembersYet()
    execute(addMemberSql(Number(roadmapId), principal), `add ${principal} to roadmap ${roadmapId}`)
    console.log(`\n${principal} reaches roadmap ${roadmapId}`)
    warnIfFirst(wasEmpty, principal)
    break
  }

  case 'remove-member': {
    const [principal] = args
    if (!principal) fail(USAGE)
    execute(removeMemberSql(principal), `remove ${principal}`)
    console.log(`\n${principal} reaches no roadmap`)
    break
  }

  case 'add-delegate': {
    const [principal] = args
    if (!principal) fail(USAGE)
    execute(addDelegateSql(principal), `add delegate ${principal}`)
    console.log(`\n${principal} may act on behalf of members`)
    break
  }

  case 'remove-delegate': {
    const [principal] = args
    if (!principal) fail(USAGE)
    execute(removeDelegateSql(principal), `remove delegate ${principal}`)
    console.log(`\n${principal} may no longer act on behalf of members`)
    break
  }

  default:
    fail(USAGE)
}
