import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { seedSql } from './seed-sql.mjs'

// For the local database only. The live roadmap changes through an import in the
// app (Settings, or POST /api/import), which checks the file against every rule,
// shows what it changes, and refuses one made from an older revision. None of
// that happens here: this writes whatever the file says. See seed-sql.mjs for
// what the statements do and leave alone.
//
// Pass a path to seed a different file, e.g. the tracked example:
//   node tools/seed/to-sql.mjs seed/roadmap.example.json
//
// Pass --with-dates when the file carries a new calendar on purpose. Without it,
// the planned dates of items already in the database are left as they are.
//
// Pass --roadmap N to load it into roadmap N rather than the first. The roadmap
// must exist: tools/roadmaps creates one.

const root = new URL('../../', import.meta.url)
const args = process.argv.slice(2)
const withDates = args.includes('--with-dates')
const roadmapAt = args.indexOf('--roadmap')
const roadmapId = roadmapAt === -1 ? 1 : Number(args[roadmapAt + 1])
const input =
  args.find((arg, index) => !arg.startsWith('--') && index !== roadmapAt + 1) ?? 'seed/roadmap.json'
const seedPath = new URL(input, root)

if (!Number.isInteger(roadmapId) || roadmapId < 1) {
  console.error(`--roadmap takes a roadmap id, a whole number from 1; got ${args[roadmapAt + 1]}`)
  process.exit(1)
}
if (!existsSync(seedPath)) {
  console.error(`${input} not found. The roadmap is private and lives outside this repository.`)
  console.error(`Copy seed/roadmap.example.json to seed/roadmap.json to start one.`)
  process.exit(1)
}

const raw = readFileSync(seedPath, 'utf8')
const seed = JSON.parse(raw)
const version = createHash('sha256').update(raw).digest('hex').slice(0, 12)
const statements = seedSql(seed, { roadmapId, withDates, version })
const workItems = seed.workItems ?? []

mkdirSync(new URL('build/', root), { recursive: true })
writeFileSync(
  new URL('build/seed.sql', root),
  `-- Generated by tools/seed/to-sql.mjs from ${input} for roadmap ${roadmapId} — do not edit.\n` +
    `-- Seed version ${version}: ${seed.items.length} items, ${workItems.length} work items, ` +
    `${seed.phases.length} phases, ` +
    `${Object.keys(seed.skills).length} skills.\n\n` +
    `${statements.join('\n\n')}\n`,
)

console.log(
  `build/seed.sql${withDates ? ' (with dates)' : ''} — roadmap ${roadmapId}, ` +
    `${seed.items.length} items, ${workItems.length} work items, ` +
    `${seed.phases.length} phases, ` +
    `${seed.blackouts.length} blackouts, ${Object.keys(seed.skills).length} skills, ` +
    `seed version ${version}`,
)
